INSERT INTO DETALLEGLOBAL SELECT "B1" + RTRIM(PEDIDOG),PRODUCTO,CANTASURTIR,0,0,0,0,0,0 FROM DETALLEBACK WHERE CANTASURTIR > 0 AND SITUACION = 1 AND CAST(SUBSTRING(PEDIDOG,5,5) AS INT ) < 10000
INSERT INTO PEDPROVE SELECT SUBSTRING(PEDIDOG,1,3), PEDIDOG,FECHA,1,NULL,0,NULL,2,NULL,NULL,NULL,NULL,0,PEDIDOG,1 FROM DETALLEBACK WHERE CANTASURTIR > 0 AND SITUACION = 1 AND CAST(SUBSTRING(PEDIDOG,5,5) AS INT ) < 10000 AND PEDIDOG <> "K02-9" GROUP BY PEDIDOG,FECHA

SELECT * FROM PEDPROVE WHERE NOT PP_PEDBACK IS NULL
SELECT * FROM DETALLEBACK WHERE CANTASURTIR > 0 AND SITUACION = 1 
