--TRASLADOS ENTRE TIENDAS
DELETE FROM DETALLETRASLADO
DELETE FROM TRASLADOS
--PEDIDOS DE ABASTECIMIENTO
DELETE FROM PEDIDOS
DELETE FROM DETALLEFACTURA
--PEDIDOS DE PEDIDOS DE COMPRA
DELETE FROM PEDPROVE
DELETE FROM DETALLEGLOBAL
--AJUSTES DE INVENTARIO
DELETE FROM AJUSTES
DELETE FROM DETALLEAJUSTES
--VENTAS
DELETE FROM VENTAS_DET 
DELETE FROM VENTAS
--FACTURAS
DELETE FROM DETALLEFACTURA
DELETE FROM FACTURAS
DELETE FROM FACVENTA
DELETE FROM FACVTAMAY
DELETE FROM FACVENTA_DET WHERE FECHA_DET <= "01-01-2003"
--ABONS
DELETE FROM ABONOS
DELETE FROM AGENDA
--BACKORDER
DELETE FROM DETALLEBACK
DELETE FROM BACKORDER
--NOTAS DE ENTRADA
DELETE FROM NOTAENTRADA
DELETE FROM DETALLENOTA
--CATALOGO CLIENTES
DELETE FROM CATCLIENTE
DELETE FROM CATCORTE
DELETE FROM CATPAGOS
DELETE FROM CATREPRE
DELETE FROM CODIGOS
DELETE FROM DESCPRODHIS
DELETE FROM FOLIOS
DELETE FROM FOLPOLIZA
DELETE FROM POLCONTADO
DELETE FROM PREVENTAS
DELETE FROM PRODBORRA
DELETE FROM VALCHEQ
DELETE FROM VENTASAC
DELETE FROM VALES
DELETE FROM DIASVER
DELETE FROM INVCORTE