--Salida de productos
--Traslados
DELETE FROM INVTEMP
INSERT INTO INVTEMP (PRODUCTO,MOVIMIENTO) SELECT DT_PRODUCTO,SUM(DT_CANTIDAD) FROM DETALLETRASLADO,TRASLADOS WHERE DT_CLAVE = T_CLAVE AND T_FECHA >= "DIC 12,2000" AND T_MOTIVOCANCELA IS NULL AND T_enviado = 1 GROUP BY DT_PRODUCTO
UPDATE INVENTARIO SET SALENV = MOVIMIENTO FROM INVTEMP WHERE PRODUCTO = INPROD
--Entrada de productos
--Pedidos pro proveedor
DELETE FROM INVTEMP
INSERT INTO invtemp SELECT DG_PRODUCTO, SUM(DG_CANTREAL)+SUM(DG_PROMOCIONR) FROM PEDPROVE,DETALLEGLOBAL WHERE PP_PEDIDO = DG_PEDIDO AND PP_FECRECIBE >= "DIC 12,2000" GROUP BY DG_PRODUCTO
UPDATE INVENTARIO SET ENTPEDP = MOVIMIENTO FROM INVTEMP WHERE PRODUCTO = INPROD
--Pedidos Instantaneos o sugeridos
DELETE FROM INVTEMP
INSERT INTO InvTemp SELECT DF_PROD, SUM(DF_CANTREAL) FROM PEDIDOS,DETALLEFACTURA WHERE P_PEDIDO = DF_PEDIDO AND P_FECENTREAL >= "DIC 12,2000" GROUP BY DF_PROD
UPDATE INVENTARIO SET ENTPED = MOVIMIENTO FROM INVTEMP WHERE PRODUCTO = INPROD
--Ajustes
DELETE FROM INVTEMP
INSERT INTO InvTemp SELECT da_producto,SUM(DA_cantidad) FROM AJUSTES,DETALLEAJUSTES WHERE A_CLAVE = DA_CLAVE and a_fecha >= "DIC 12,2000"  group by da_producto
UPDATE INVENTARIO SET ajustes = MOVIMIENTO FROM INVTEMP WHERE PRODUCTO = INPROD
--Devoluciones, llegadas de envasadoras, Cajiga.
DELETE FROM INVTEMP
INSERT INTO INVTEMP (PRODUCTO,MOVIMIENTO) SELECT DT_PRODUCTO,SUM(DT_CANTIDAD) FROM DETALLETRASLADO,TRASLADOS WHERE DT_CLAVE = T_CLAVE AND T_FECHA >= "DIC 12,2000" AND T_MOTIVOCANCELA IS NULL AND T_entrada = 1 GROUP BY DT_PRODUCTO
UPDATE INVENTARIO SET ajustes = MOVIMIENTO FROM INVTEMP WHERE PRODUCTO = INPROD



